;(function(window){'use strict';var lastTime=0;var prefixes='webkit moz ms o'.split(' ');var requestAnimationFrame=window.requestAnimationFrame;var cancelAnimationFrame=window.cancelAnimationFrame;var prefix;for(var i=0;i<prefixes.length;i++){if(requestAnimationFrame&&cancelAnimationFrame){break;}
prefix=prefixes[i];requestAnimationFrame=requestAnimationFrame||window[prefix+'RequestAnimationFrame'];cancelAnimationFrame=cancelAnimationFrame||window[prefix+'CancelAnimationFrame']||window[prefix+'CancelRequestAnimationFrame'];}
if(!requestAnimationFrame||!cancelAnimationFrame){requestAnimationFrame=function(callback,element){var currTime=new Date().getTime();var timeToCall=Math.max(0,16-(currTime-lastTime));var id=window.setTimeout(function(){callback(currTime+timeToCall);},timeToCall);lastTime=currTime+timeToCall;return id;};cancelAnimationFrame=function(id){window.clearTimeout(id);};}
function extend(a,b){for(var key in b){if(b.hasOwnProperty(key)){a[key]=b[key];}}
return a;}
function getMousePos(e){var posx=0;var posy=0;if(!e)var e=window.event;if(e.pageX||e.pageY){posx=e.pageX;posy=e.pageY;}
else if(e.clientX||e.clientY){posx=e.clientX+document.body.scrollLeft
+document.documentElement.scrollLeft;posy=e.clientY+document.body.scrollTop
+document.documentElement.scrollTop;}
return{x:posx,y:posy}}
function throttle(fn,delay){var allowSample=true;return function(e){if(allowSample){allowSample=false;setTimeout(function(){allowSample=true;},delay);fn(e);}};}
function TiltFx(el,options){this.el=el;this.options=extend({},this.options);extend(this.options,options);this._init();this._initEvents();}
TiltFx.prototype.options={extraImgs:2,opacity:0.7,bgfixed:true,movement:{perspective:1000,translateX:-10,translateY:-10,translateZ:20,rotateX:2,rotateY:2,rotateZ:0}}
TiltFx.prototype._init=function(){this.tiltWrapper=document.createElement('div');this.tiltWrapper.className='tilt';this.tiltImgBack=document.createElement('div');this.tiltImgBack.className='tilt__back';this.tiltImgBack.style.backgroundImage='url('+this.el.src+')';this.tiltWrapper.appendChild(this.tiltImgBack);if(this.options.extraImgs<1){this.options.extraImgs=1;}
else if(this.options.extraImgs>5){this.options.extraImgs=5;}
if(!this.options.movement.perspective){this.options.movement.perspective=0;}
this.imgElems=[];for(var i=0;i<this.options.extraImgs;++i){var el=document.createElement('div');el.className='tilt__front';el.style.backgroundImage='url('+this.el.src+')';el.style.opacity=this.options.opacity;this.tiltWrapper.appendChild(el);this.imgElems.push(el);}
if(!this.options.bgfixed){this.imgElems.push(this.tiltImgBack);++this.options.extraImgs;}
this.el.parentNode.insertBefore(this.tiltWrapper,this.el);this.el.parentNode.removeChild(this.el);this.view={width:this.tiltWrapper.offsetWidth,height:this.tiltWrapper.offsetHeight};};TiltFx.prototype._initEvents=function(){var self=this,moveOpts=self.options.movement;this.tiltWrapper.addEventListener('mousemove',function(ev){requestAnimationFrame(function(){var mousepos=getMousePos(ev),docScrolls={left:document.body.scrollLeft+document.documentElement.scrollLeft,top:document.body.scrollTop+document.documentElement.scrollTop},bounds=self.tiltWrapper.getBoundingClientRect(),relmousepos={x:mousepos.x-bounds.left-docScrolls.left,y:mousepos.y-bounds.top-docScrolls.top};for(var i=0,len=self.imgElems.length;i<len;++i){var el=self.imgElems[i],rotX=moveOpts.rotateX?2*((i+1)*moveOpts.rotateX/self.options.extraImgs)/self.view.height*relmousepos.y-((i+1)*moveOpts.rotateX/self.options.extraImgs):0,rotY=moveOpts.rotateY?2*((i+1)*moveOpts.rotateY/self.options.extraImgs)/self.view.width*relmousepos.x-((i+1)*moveOpts.rotateY/self.options.extraImgs):0,rotZ=moveOpts.rotateZ?2*((i+1)*moveOpts.rotateZ/self.options.extraImgs)/self.view.width*relmousepos.x-((i+1)*moveOpts.rotateZ/self.options.extraImgs):0,transX=moveOpts.translateX?2*((i+1)*moveOpts.translateX/self.options.extraImgs)/self.view.width*relmousepos.x-((i+1)*moveOpts.translateX/self.options.extraImgs):0,transY=moveOpts.translateY?2*((i+1)*moveOpts.translateY/self.options.extraImgs)/self.view.height*relmousepos.y-((i+1)*moveOpts.translateY/self.options.extraImgs):0,transZ=moveOpts.translateZ?2*((i+1)*moveOpts.translateZ/self.options.extraImgs)/self.view.height*relmousepos.y-((i+1)*moveOpts.translateZ/self.options.extraImgs):0;el.style.WebkitTransform='perspective('+moveOpts.perspective+'px) translate3d('+transX+'px,'+transY+'px,'+transZ+'px) rotate3d(1,0,0,'+rotX+'deg) rotate3d(0,1,0,'+rotY+'deg) rotate3d(0,0,1,'+rotZ+'deg)';el.style.transform='perspective('+moveOpts.perspective+'px) translate3d('+transX+'px,'+transY+'px,'+transZ+'px) rotate3d(1,0,0,'+rotX+'deg) rotate3d(0,1,0,'+rotY+'deg) rotate3d(0,0,1,'+rotZ+'deg)';}});});this.tiltWrapper.addEventListener('mouseleave',function(ev){setTimeout(function(){for(var i=0,len=self.imgElems.length;i<len;++i){var el=self.imgElems[i];el.style.WebkitTransform='perspective('+moveOpts.perspective+'px) translate3d(0,0,0) rotate3d(1,1,1,0deg)';el.style.transform='perspective('+moveOpts.perspective+'px) translate3d(0,0,0) rotate3d(1,1,1,0deg)';}},60);});window.addEventListener('resize',throttle(function(ev){self.view={width:self.tiltWrapper.offsetWidth,height:self.tiltWrapper.offsetHeight};},50));};function init(){[].slice.call(document.querySelectorAll('img.tilt-effect')).forEach(function(img){new TiltFx(img,JSON.parse(img.getAttribute('data-tilt-options')));});}
$(".tilt-wrap").imagesLoaded(function(){init();});window.TiltFx=TiltFx;})(window);